apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: rancher/cowsay:latest
        command: ["cowsay"]
        args: ["test2"]
