apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
      - name: cowsay
        image: rancher/cowsay:latest
        command: ["sh","-c"]
        args: ["while true; do cowsay test2; sleep 20; done"]
